apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAic3RlcGhwdW5rZnJvbXNhbWFyYSIsCiAgICAgICJwYXNzd29yZCI6ICJnaHBfMFVhSHJlQkdSUTF0VzFiMTBpVmdOZkt0WFFFN0c1NEpzYk5hIiwKICAgICAgImF1dGgiOiAiYzNSbGNHaHdkVzVyWm5KdmJYTmhiV0Z5WVRwbmFIQmZNRlZoU0hKbFFrZFNVVEYwVnpGaU1UQnBWbWRPWmt0MFdGRkZOMGMxTkVwellrNWgiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
