# Global settings
global:
  namespace: cinemaabyss
  domain: cinemaabyss.example.com

# Image pull secrets
imagePullSecrets:
  dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAic3RlcGhwdW5rZnJvbXNhbWFyYSIsCiAgICAgICJwYXNzd29yZCI6ICJnaHBfMFVhSHJlQkdSUTF0VzFiMTBpVmdOZkt0WFFFN0c1NEpzYk5hIiwKICAgICAgImF1dGgiOiAiYzNSbGNHaHdkVzVyWm5KdmJYTmhiV0Z5WVRwbmFIQmZNRlZoU0hKbFFrZFNVVEYwVnpGaU1UQnBWbWRPWmt0MFdGRkZOMGMxTkVwellrNWgiCiAgICB9CiAgfQp9Cg==
# Database configuration
database:
  host: postgres
  port: 5432
  name: cinemaabyss
  user: postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

# Monolith configuration
monolith:
  enabled: true
  image:
    repository: ghcr.io/stephpunkfromsamara/architecture-cinemaabyss/monolith
    tag: sha-2d28435@sha256:a5e6e714406e15b150a46187c15e46a453e37eea0fde5384e7748170663e3bf2
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP

# Proxy service configuration
proxyService:
  enabled: true
  image:
    repository: ghcr.io/stephpunkfromsamara/architecture-cinemaabyss/proxy-service
    tag: sha-2d28435@sha256:47b6ddba6999ca45484ec854d3babf03dfcd1e9a1f193c04c82f84350ee1367e
    pullPolicy: Always
  replicas: 1
  env:
    MOVIES_SERVICE_URL: "http://movies-service:8081"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
    targetPort: 8000
    type: ClusterIP

# Movies service configuration
moviesService:
  enabled: true
  image:
    repository: ghcr.io/stephpunkfromsamara/architecture-cinemaabyss/movies-service
    tag: sha-2d28435@sha256:04754816ba5b83ea069363695dcb4e10b9e9d57b9c2b2e5b5699c422c02b9a1a
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8081
    targetPort: 8081
    type: ClusterIP

# Events service configuration
eventsService:
  enabled: true
  image:
    repository: ghcr.io/stephpunkfromsamara/architecture-cinemaabyss/events-service
    tag: sha-2d28435@sha256:29599471083d27bf0cc6458bd046e1f5b4a319f68471448f9f088048c32397b8
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 8082
    targetPort: 8082
    type: ClusterIP

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: wurstmeister/kafka
    tag: 2.13-2.7.0
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
  topics:
    - name: movie-events
      partitions: 1
      replicationFactor: 1
    - name: user-events
      partitions: 1
      replicationFactor: 1
    - name: payment-events
      partitions: 1
      replicationFactor: 1

# Zookeeper configuration
zookeeper:
  enabled: true
  image:
    repository: wurstmeister/zookeeper
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: cinemaabyss.example.com
      paths:
        - path: /
          pathType: Prefix
          service: proxy-service
          port: 8000
        - path: /api/events
          pathType: Prefix
          service: events-service
          port: 8082

# Application configuration
config:
  # Strangler Fig configuration
  gradualMigration: "true"
  moviesMigrationPercent: "100"
